import React from 'react'
import Head from 'next/head' //this is same thing as Head in html. In next.js, you just have to import it like this

import styles from '../styles/style'

import Navbar from './Navbar'
import Footer from './Footer'

const Layout = ({ children }) => {
  return (
    // below is where you can change background color of app
    <div className="bg-primary layout w-full overflow-hidden">
    {/* <div className="layout w-full overflow-hidden"> */}
      <Head>
        <title>U&G Market Research Store</title>
        {/* Below, is where maybe the favicon goes. Might not need it though. Might just have to create a favicon we like and name it favicon.ico and replace the one in public folder. Also, once again, don't don't if need this meta stuff - don't think i do */}
        {/* <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <header>
        <div className={`{styles.paddingX} {styles.flexCenter}`}>
        {/* <div className={`sm:px-16 px-6 flex justify-center items-center`}> */}
          {/* I HAVE LEARNED THE styles.paddingX - anything imported is not working here, but now seems to be working on Navbar.jsx, so i just put it there. It works here though if you actually hard code it like it is on style.js. ALSO, maybe a double navbar wheree the top one has the shopping cart and bottom has regular stuff might be nice? */}
          {/* <div className={`${styles.boxWidth}`}> */}
          <div className={`${styles.boxWidth}`}>
            <Navbar />
          </div>
        </div>
        {/* There seems to be a little bit more margin below navbar and main content in first ecommerce site - change if want in navbar with margin bottom or main content with margin top */}
      </header>
      <main className="main-container">
        {/* Below, To make Component from _app.js appear in our app, use thing in react where whatever you pass inside your component, you get access to that through prop called 'children' */}
        {children}
      </main>
      <footer>
        <Footer />
      </footer>
    </div>
  )
}

export default Layout