import React from 'react'
import Head from 'next/head' //this is same thing as Head in html. In next.js, you just have to import it like this

import Navbar from './Navbar'
import Footer from './Footer'

const Layout = ({ children }) => {
  return (
    <div className="layout">
      <Head>
        <title>U&G Market Research Store</title>
        {/* Below, is where maybe the favicon goes. Might not need it though. Might just have to create a favicon we like and name it favicon.ico and replace the one in public folder. Also, once again, don't don't if need this meta stuff - don't think i do */}
        {/* <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <header>
        <Navbar />
      </header>
      <main className="main-container">
        {/* Below, To make Component from _app.js appear in our app, use thing in react where whatever you pass inside your component, you get access to that through prop called 'children' */}
        {children}
      </main>
      <footer>
        <Footer />
      </footer>
    </div>
  )
}

export default Layout